### ISSUE TITLE
[FEATURE]: Customisation of attribute the tooltip is bound to

### ISSUE THREAD

**Issue by projct1** [jackdomleo7/Cooltipz.css#63]
Will be epic good, if can be use not aria-label attribute for content. I want use title attribute, for SEO reasons.

**Comment by jackdomleo7** [comment]
@projct1 this is an interesting idea, and one I can surely work on as I have an idea. The default will and should always be `aria-label`, but I can make it so you as the consuming developer can customise this.

However, I'm not sure how using `title` over `aria-label` will improve SEO. Search engines don't know the context so ultimately won't care, plus `title` has [accessibility concerns](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns) attached to it anyway, so not sure search engines would see this as a good thing. But this is beside the point of the actual feature request.

**Comment by jackdomleo7** [comment]
Look out for this in a future release over the next couple of days.
The only caveat to this was, it can only be done customised via SCSS, and cannot be customised by just using the CSS stylesheet.

**Comment by jackdomleo7** [comment]
Released in [v2.1.0](https://github.com/jackdomleo7/Cooltipz.css/releases/tag/v2.1.0)
