### ISSUE TITLE
[FEATURE]: arrow offset

### ISSUE THREAD

**Issue by asmith20002** [jackdomleo7/Cooltipz.css#89]
Hello,

I'd like to suggest a feature. When the border radius of the tip is high, the arrow leaves a gap:

![cooltipz](https://github.com/jackdomleo7/Cooltipz.css/assets/17809451/dc1e3ec2-0b2c-4cb9-afe3-2a3efcbfc4eb)

The feature is the ability to translate this arrow.

```
--cooltipz-arrow-side-offset: 5px;
```

Called it "side" because it should be none when it is centered.

In my case it would be:

```
right: calc(var(--cooltipz-arrow-size, .3125rem)/2 + var(--cooltipz-arrow-side-offset));
``` 

Thanks for your work 👍

**Comment by jackdomleo7** [comment]
Hi, seems like a good idea! I'm away on holiday for the next few weeks but will take a look at implementing this when I return 🙂

**Comment by jackdomleo7** [comment]
Thanks for the suggestion. ❤️ This new feature is included in [v2.3.0](https://github.com/jackdomleo7/Cooltipz.css/releases/tag/v2.3.0).

The new variable is called `--cooltipz-arrow-offset`.

Please refer to [docs](https://cooltipz.jackdomleo.dev/#customise).

**Comment by asmith20002** [comment]
Thanks for the effort. I've checked the implemented feature, I'm afraid it is not functioning as I expected. Maybe you have implemented it a different way.

By setting `--cooltipz-arrow-offset: 5px;` on a fresh version 2.3.0:

**Issue:**
`data-cooltipz-dir="bottom"` => even though it is a centered arrow, it moves the arrow to the right by 5 pixels.
**expected:**
For direction top, bottom, left and right the arrow should be centered and the offset shouldn't apply. (I've mentioned it in my original post)

**Issue:**
`data-cooltipz-dir="bottom-right"` => The tooltip is on the right but the arrow is translated even further to the right out of the tooltip.
**expected:**
If the tooltip is on the right, the offset of the arrow should move it to the left.

If we set `--cooltipz-arrow-offset: 5px;`, the arrow should always move inward the box. Otherwise one of `bottom-left` or `bottom-right` directions will break.

If I'm misinterpreting this feature, please let me know.

**Comment by jackdomleo7** [comment]
@asmith20002 Could you raise an issue with a reproductive link, or provide a pull request as I'm not fully understanding. The offsetting seems to be working fine but I'm not following your request very clearly.

I implemented a different way because the way you provided only worked for a few scenarios.
