### ISSUE TITLE
data-cooltipz-dir="top" not readable and negates element

### ISSUE THREAD

**Issue by jpgateaux** [jackdomleo7/Cooltipz.css#90]
have this in html
`<div  class="custom--tooltip scrollBtn up noprint" data-cooltipz-dir="top" aria-label="Go to top" onclick="scrollToTop()" ><i style="" class="fa fa-chevron-up"></i></div>`

it makes div disappear 

when I remove data-cooltipz-dir="top"  the html displays but foesn't show tooltip

i succesfully  used in another app with no problems  

Can;t figure out

**Comment by jackdomleo7** [comment]
Hi, thanks for raising an issue. Unfortunately, you have not given me much to go off. It's likely the CSS clashing, but I have no idea what CSS you're using. If you could create a reproduction environment (GitHub project, CodePen, etc) that clearly demonstrates the bug, that would be great.

**Comment by jackdomleo7** [comment]
Closing this bug due to inactivity
