### ISSUE TITLE
[BUG]: gap 

### ISSUE THREAD

**Issue by bc-devle** [jackdomleo7/Cooltipz.css#93]
When we use --cooltipz-border-width : 1px (at least on chrome). There is a gap between tooltip border and tooltip arrow
![image](https://github.com/jackdomleo7/Cooltipz.css/assets/101404772/2bc6dc64-6de0-4e4d-aad2-cba9fd99e44b)

**Comment by jackdomleo7** [comment]
Hi @bc-devle, thank you for your contribution. Could you please provide a reproduction of this bug either in something like CodePen or Sandbox that isolates the issue you're seeing?

I have seen this before though and suspect it is not related to the CSS. I have seen it on lower resolution devices that are below or equal to 1080p. I'm not 100% how to resolve that works for every scenario but it's likely that if you use a different device, you may not see this.

**Comment by bc-devle** [comment]
Hello Jack, good point, there is no gap in codepen : https://codepen.io/reign17/pen/RwEMKdv
seems to be related to my project...

**Comment by jackdomleo7** [comment]
It's either your project, your device or where the tooltip is positioned - I've found if the exact same tooltip is positioned in a different position, then the issue doesn't occur. It's a bit of an awkward one really.

Going to close this issue for now. Thanks 🙂

**Comment by bc-devle** [comment]
Its a problem with margin-top calculation in :after. I fixed it in myu project by overriding --cooltipz-arrow-size: 0.4rem;
